/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2018-08-21 07:52:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insertForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<META http-equiv=\"page-enter\" content=\"BlendTrans(Duration=0.5)\" />\r\n");
      out.write("<link rel = \"stylesheet\" type = \"text/css\" href = \"body_css_info.css\">\r\n");
      out.write("<title>Travel Diary</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 입력하지 않았을 경우.. -->\r\n");
      out.write("<style>\r\n");
      out.write("@font-face { font-family: 'NANUMBARUNPENB'; src: url(font/NANUMBARUNPENB.TTF) format('truetype'); } \r\n");
      out.write("@font-face{font-family: amaticsc-bold; src:url('font/AmaticSC-Bold.ttf')}\r\n");
      out.write("body { \r\n");
      out.write("\tfont-family: NANUMBARUNPENB; \r\n");
      out.write("\tbackground-image: url(https://i.pinimg.com/originals/bf/95/f9/bf95f997e1641314be464c530b4a8825.jpg);\r\n");
      out.write("\tbackground-size: 100%;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("table{\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tpadding:5%;\r\n");
      out.write("}\r\n");
      out.write(".desti{\r\n");
      out.write("\twidth: 750px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write(".title{\r\n");
      out.write("\twidth: 750px;\r\n");
      out.write("}\r\n");
      out.write(".month{\r\n");
      out.write("\twidth: 40px;\r\n");
      out.write("}\r\n");
      out.write(".day{\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("}\r\n");
      out.write(".money{\r\n");
      out.write("\twidth :300px;\r\n");
      out.write("}\r\n");
      out.write(".move{\r\n");
      out.write("\tmargin-right:20px;\r\n");
      out.write("}\r\n");
      out.write(".button{\r\n");
      out.write("\tmargin-right:40px;\r\n");
      out.write("\tfont-family: NANUMBARUNPENB;\r\n");
      out.write("\tfont-size:13pt;\r\n");
      out.write("}\r\n");
      out.write("td{\r\n");
      out.write("\tpadding-bottom:40px;\r\n");
      out.write("}\r\n");
      out.write(".name_c{\r\n");
      out.write("\tcolor: #A9E2F3;\r\n");
      out.write("\tfont-size: 30pt;\r\n");
      out.write("\tmargin-top:10px;\r\n");
      out.write("}\r\n");
      out.write(".font2{\r\n");
      out.write("\tfont-family: amaticsc-bold;\r\n");
      out.write("\tfont-size: 4em;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tmargin-top: 2%;\r\n");
      out.write("}\r\n");
      out.write("textarea  \r\n");
      out.write("{  \r\n");
      out.write("   font-family: NANUMBARUNPENB;  \r\n");
      out.write("   font-size: 15px;   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body:before{\r\n");
      out.write("  content:'';\r\n");
      out.write("  height:100%;\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  vertical-align:middle;\r\n");
      out.write("}\r\n");
      out.write("button{\r\n");
      out.write("  background:black;\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  border:none;\r\n");
      out.write("  position:relative;\r\n");
      out.write("  height:30px;\r\n");
      out.write("  font-size:0.8em;\r\n");
      out.write("  padding:0 2em;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("  margin-bottom: 2%;\r\n");
      out.write("  transition:800ms ease all;\r\n");
      out.write("  outline:none;\r\n");
      out.write("}\r\n");
      out.write("button:hover{\r\n");
      out.write("  background:#fff;\r\n");
      out.write("  color:black;\r\n");
      out.write("}\r\n");
      out.write("button:before,button:after{\r\n");
      out.write("  content:'';\r\n");
      out.write("  position:absolute;\r\n");
      out.write("  top:0;\r\n");
      out.write("  right:0;\r\n");
      out.write("  height:2px;\r\n");
      out.write("  width:0;\r\n");
      out.write("  background: black;\r\n");
      out.write("  transition:400ms ease all;\r\n");
      out.write("}\r\n");
      out.write("button:after{\r\n");
      out.write("  right:inherit;\r\n");
      out.write("  top:inherit;\r\n");
      out.write("  left:0;\r\n");
      out.write("  bottom:0;\r\n");
      out.write("}\r\n");
      out.write("button:hover:before,button:hover:after{\r\n");
      out.write("  width:100%;\r\n");
      out.write("  transition:800ms ease all;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("var rgx1 = /\\D/g;  // /[^0-9]/g 와 같은 표현\r\n");
      out.write("var rgx2 = /(\\d+)(\\d{3})/; \r\n");
      out.write("function getNumber(obj){\r\n");
      out.write("\t\r\n");
      out.write("     var num01;\r\n");
      out.write("     var num02;\r\n");
      out.write("     num01 = obj.value;\r\n");
      out.write("     num02 = num01.replace(rgx1,\"\");\r\n");
      out.write("     num01 = setComma(num02);\r\n");
      out.write("     obj.value =  num01;\r\n");
      out.write("}\r\n");
      out.write("//천단위 콤마 찍기\r\n");
      out.write("function setComma(inNum){\r\n");
      out.write("     \r\n");
      out.write("     var outNum;\r\n");
      out.write("     outNum = inNum; \r\n");
      out.write("     while (rgx2.test(outNum)) {\r\n");
      out.write("          outNum = outNum.replace(rgx2, '$1' + ',' + '$2');\r\n");
      out.write("      }\r\n");
      out.write("     return outNum;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("function pop_open(){\r\n");
      out.write("\t\r\n");
      out.write("\t var form = document.sendform;\r\n");
      out.write("\t var url = \"result_wtog.jsp\"\r\n");
      out.write("\t \r\n");
      out.write("\t var left = Math.ceil((window.screen.width - 530)/2);\r\n");
      out.write("     var top = Math.ceil((window.screen.height - 350)/2);\r\n");
      out.write("\t \r\n");
      out.write("\t window.open(\"\",\"result_wtog\",\"top=\" + top + \", left =\" + left + \", width=530px, height=350px\");\r\n");
      out.write("\t form.action = url //팝업창 URL\r\n");
      out.write("\t form.target=\"result_wtog\";\r\n");
      out.write("\t form.method = \"post\"\r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t form.submit(); // 값을 전송한다.\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("\t<a href=\"index.jsp\"><div style = \"background-color:black; margin: 2%; padding: 0.5px\">\r\n");
      out.write("\t\t<p class = \"font2\"> add new diary</p>\r\n");
      out.write("\t</div></a>\r\n");
      out.write("</center>\r\n");
      out.write("<center>\r\n");
      out.write("\t<table border = 0 width = \"800px\" style = \"margin-top:5px\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<label># 대표이미지</label><br><br>\r\n");
      out.write("\t\t\t<input type = file name = \"upload\" size = 40>\r\n");
      out.write("\t\t\t<div id = 'holder'>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<label># 컨셉</label><br><br>\r\n");
      out.write("\t\t\t<input type = \"text\" name = \"concept\" class = \"title\" id = \"concept\" placeholder = \"예) 친구와 함께 떠나는 먹방여행\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<label># 어디로 갈까?</label><br><br>\r\n");
      out.write("\t\t<input type = \"text\" placeholder = \"예) 일본, 도쿄\" name = \"desti\" class = \"desti\" id = \"desti\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<label># 어디로 갈까?(영문)</label><br><br>\r\n");
      out.write("\t\t<input type = \"text\" placeholder = \"예) Japan, Tokyo\" name = \"e_desti\" class = \"desti\" id = \"desti\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<label># 얼마나 갈까?</label><br><br>\r\n");
      out.write("\t\t\t<input type = \"date\" name = \"s_day\"> ~ <input type = \"date\" name = \"e_day\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<label># 얼마 가지고 갈까?</label><br><br>\r\n");
      out.write("\t\t\t<input type = \"text\" name = \"money\" class = \"money\" id = \"money\" onchange=\"getNumber(this);\" onkeyup=\"getNumber(this);\">원\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<label># 어떻게 갈까?</label><br><br>\r\n");
      out.write("\t\t\t<input type = \"checkbox\" name = \"move\" value = \"비행기\"><label class =\"move\">비행기</label>\r\n");
      out.write("\t\t\t<input type = \"checkbox\" name = \"move\" value = \"배\"><label class =\"move\">배</label>\r\n");
      out.write("\t\t\t<input type = \"checkbox\" name = \"move\" value = \"차\"><label class =\"move\">자동차</label>\r\n");
      out.write("\t\t\t<input type = \"checkbox\" name = \"move\" value = \"버스\"><label class =\"move\">버스</label>\r\n");
      out.write("\t\t\t<input type = \"checkbox\" name = \"move\" value = \"걸어서\"><label class =\"move\">걸어서</label>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<label># 누구랑 갈까?</label><br><br>\r\n");
      out.write("\t\t\t<input type = \"radio\" name = \"who\" value = \"together\"><label class =\"move\">같이가자</label>\r\n");
      out.write("\t\t\t<input type = \"radio\" name = \"who\" value = \"solo\"><label class =\"move\">혼자가자</label>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<label># 여행 코스를 짜볼까?</label><br><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<textarea rows=\"30\" cols=\"200\"></textarea>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("//행개수\r\n");
      out.write("var count = 1;\r\n");
      out.write("//최대 행개수\r\n");
      out.write("var full_count = 10;\r\n");
      out.write("//이름 값\r\n");
      out.write("var name = 1;\r\n");
      out.write("  //행추가\r\n");
      out.write("  function add_tr() {\r\n");
      out.write(" //최대 행개수보다 크면 리턴\r\n");
      out.write(" if(count>full_count){\r\n");
      out.write("  alert(\"최대10개까지만 가능합니다.\");\r\n");
      out.write("  return;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" //추가할 HTML\r\n");
      out.write(" var add_cell1 = \"<p id = 'status'><br><input type='file' size=40 name = 'img\"+name+\"'>\"; \r\n");
      out.write(" var add_cell2 = \"<textarea rows='10' cols='50' name='text\" + name + \"'>\";\r\n");
      out.write(" \r\n");
      out.write(" //행추가할 테이블 가져오기\r\n");
      out.write(" var table_name = document.getElementById(\"text_table\");\r\n");
      out.write(" \r\n");
      out.write(" //tr만들기\r\n");
      out.write(" var new_row = table_name.insertRow();\r\n");
      out.write(" \r\n");
      out.write(" //td만들기\r\n");
      out.write(" var new_cell1 = new_row.insertCell();\r\n");
      out.write(" var new_cell2 = new_row.insertCell();\r\n");
      out.write(" \r\n");
      out.write(" //td안에 넣을 HTML\r\n");
      out.write(" new_cell1.innerHTML = add_cell1;\r\n");
      out.write(" new_cell2.innerHTML = add_cell2;\r\n");
      out.write(" //행추가할때마다 행개수 +1\r\n");
      out.write(" count++;\r\n");
      out.write(" name++;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  //행삭제\r\n");
      out.write("  function delete_tr() {\r\n");
      out.write(" //행삭제할 테이블 가져오기\r\n");
      out.write("    var table = document.getElementById('text_table');\r\n");
      out.write(" \r\n");
      out.write(" //행이 하나밖에 없으면 삭제하지 않기\r\n");
      out.write("    if (table.rows.length < 2){\r\n");
      out.write("     alert(\"더이상 삭제할수 없습니다.\");\r\n");
      out.write("     return;\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write(" //tr삭제하기\r\n");
      out.write("    table.deleteRow(table.rows.length - 1);\r\n");
      out.write(" //삭제할때마다 행개수 -1\r\n");
      out.write(" count--;\r\n");
      out.write(" name--;\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("var upload = document.getElementsByTagName('input')[0],\r\n");
      out.write("holder = document.getElementById('holder');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("upload.onchange = function (e) {\r\n");
      out.write("e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("var file = upload.files[0],\r\n");
      out.write("  reader = new FileReader();\r\n");
      out.write("reader.onload = function (event) {\r\n");
      out.write("var img = new Image();\r\n");
      out.write("img.src = event.target.result;\r\n");
      out.write("// note: no onload required since we've got the dataurl...I think! :)\r\n");
      out.write("if (img.width > 250) { // holder width\r\n");
      out.write("  img.width = 250;\r\n");
      out.write("}\r\n");
      out.write("holder.innerHTML = '';\r\n");
      out.write("holder.appendChild(img);\r\n");
      out.write("};\r\n");
      out.write("reader.readAsDataURL(file);\r\n");
      out.write("\r\n");
      out.write("return false;\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
