/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2018-08-21 06:58:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layerTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("<script src = \"http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js\"></script>\r\n");
      out.write("<script src = \"http://malsup.github.com/jquery.cycle2.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("  font-family:sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".bookWrapper {\r\n");
      out.write("  width:700px;\r\n");
      out.write("  height:450px; //multiply by 1.3 to get proper height\r\n");
      out.write("}\r\n");
      out.write(".bookBg {\r\n");
      out.write("  position:relative;\r\n");
      out.write("  background-color: #000000;\r\n");
      out.write("  width:100%;\r\n");
      out.write("  height:100%;\r\n");
      out.write("  border-radius: 12px;  \r\n");
      out.write("}\r\n");
      out.write(".centerClass {\r\n");
      out.write("  position:absolute;\r\n");
      out.write("  left:50%;\r\n");
      out.write("  top:50%;\r\n");
      out.write("}\r\n");
      out.write(".pageBg {\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  width:652px; \r\n");
      out.write("  height:422px;\r\n");
      out.write("  border-radius: 0px;\r\n");
      out.write("}\r\n");
      out.write(".spineCenter {\r\n");
      out.write("  width:2px; \r\n");
      out.write("  height:422px;\r\n");
      out.write("  border-radius: 0px;\r\n");
      out.write("  background:rgba(101,101,101,.4);\r\n");
      out.write("}\r\n");
      out.write(".pageWrapper {\r\n");
      out.write("  position:relative;\r\n");
      out.write("  width:325px;\r\n");
      out.write("  height:422px;\r\n");
      out.write("  float: left;\r\n");
      out.write("  -webkit-font-smoothing:antialiased;\r\n");
      out.write("}\r\n");
      out.write(".pageFace {\r\n");
      out.write("  position:absolute;\r\n");
      out.write("  width:325px;\r\n");
      out.write("  height:422px;\r\n");
      out.write("  overflow:hidden;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".front {\r\n");
      out.write("  background: linear-gradient(to right,  #d9d9d9 0%,#f9f9f9 3%,#ffffff 8%,#ffffff 100%);\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(".back {\r\n");
      out.write("  background: linear-gradient(to right,  #ffffff 0%,#ffffff 92%,#f9f9f9 97%,#d9d9d9 100%);\r\n");
      out.write("}\r\n");
      out.write(".pageFoldRight {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("    width:  0px;\r\n");
      out.write("    height: 0px;\r\n");
      out.write("    top:  0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    border-left-width: 1px;\r\n");
      out.write("    border-left-color: #DDDDDD;\r\n");
      out.write("    border-left-style: solid;\r\n");
      out.write("    border-bottom-width: 1px;\r\n");
      out.write("    border-bottom-color: #DDDDDD;\r\n");
      out.write("    border-bottom-style: solid;\r\n");
      out.write("    box-shadow: -5px 5px 10px #dddddd;\r\n");
      out.write("}\r\n");
      out.write(".pageFoldLeft {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("    width:  0px;\r\n");
      out.write("    height: 0px;\r\n");
      out.write("    top:  0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    border-right-width: 1px;\r\n");
      out.write("    border-right-color: #DDDDDD;\r\n");
      out.write("    border-right-style: solid;\r\n");
      out.write("    border-bottom-width: 1px;\r\n");
      out.write("    border-bottom-color: #DDDDDD;\r\n");
      out.write("    border-bottom-style: solid;\r\n");
      out.write("    box-shadow: 5px 5px 10px #dddddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("var pageLocation=[],\r\n");
      out.write("lastPage=null;\r\n");
      out.write("$Zz=0;\r\n");
      out.write("\r\n");
      out.write("TweenLite.set(\".centerClass\", {xPercent:-50, yPercent:-50});\r\n");
      out.write("TweenLite.set(\".pageWrapper\", {left: \"327px\", perspective:1000});\r\n");
      out.write("TweenLite.set(\".page\", {transformStyle:\"preserve-3d\"});\r\n");
      out.write("TweenLite.set(\".back\", {rotationY:-180});\r\n");
      out.write("TweenLite.set([\".back\", \".front\"],{backfaceVisibility:\"hidden\"});\r\n");
      out.write("\r\n");
      out.write("//All pages must have an id assigned to them in the HTML\r\n");
      out.write("$(\".page\").click(\r\n");
      out.write("function() {\r\n");
      out.write("if (pageLocation[this.id] === undefined || pageLocation[this.id] ==\"right\") {\r\n");
      out.write("\t$Zz = ($(\".left\").length)+1 ;\r\n");
      out.write("\tTweenMax.to($(this), 1, {force3D:true,rotationY:-180,transformOrigin:\"-1px top\",className:'+=left',z:$Zz,zIndex:$Zz}); \r\n");
      out.write("\tTweenLite.set($(this), {className:'-=right'}); \r\n");
      out.write("\tpageLocation[this.id]= \"left\";\r\n");
      out.write("}\r\n");
      out.write("else {\r\n");
      out.write("\t$Zz = ($(\".right\").length)+1 ;\r\n");
      out.write("\tTweenMax.to($(this), 1, {force3D:true,rotationY:0,transformOrigin:\"left top\",className:'+=right',z:$Zz,zIndex:$Zz});\r\n");
      out.write("\tTweenLite.set($(this), {className:'-=left'}); \r\n");
      out.write("\tpageLocation[this.id]= \"right\";\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("$(\".front\").hover(\r\n");
      out.write("function() {\r\n");
      out.write(" TweenLite.to($(this).find(\".pageFoldRight\"), 0.3, {width:\"50px\", height:\"50px\", backgroundImage:\"linear-gradient(45deg,  #fefefe 0%,#f2f2f2 49%,#ffffff 50%,#ffffff 100%)\"});\r\n");
      out.write("},\r\n");
      out.write("function() {\r\n");
      out.write("TweenLite.to($(this).find(\".pageFoldRight\"), 0.3, {width:\"0px\", height:\"0px\"});  \r\n");
      out.write("}\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("$(\".back\").hover(\r\n");
      out.write("function() {\r\n");
      out.write(" TweenLite.to($(this).find(\".pageFoldLeft\"), 0.3, {width:\"50px\", height:\"50px\", backgroundImage:\"linear-gradient(135deg,  #ffffff 0%,#ffffff 50%,#f2f2f2 51%,#fefefe 100%)\"});\r\n");
      out.write("},\r\n");
      out.write("function() {\r\n");
      out.write("TweenLite.to($(this).find(\".pageFoldLeft\"), 0.3, {width:\"0px\", height:\"0px\"});  \r\n");
      out.write("}\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"bookWrapper\">\r\n");
      out.write("  <div class=\"bookBg\">\r\n");
      out.write("    <div class=\"pageBg centerClass\">\r\n");
      out.write("      <div class=\"pageWrapper\">\r\n");
      out.write("        <div id=\"page3\" class=\"page\">\r\n");
      out.write("          <div class=\"pageFace front\"><h1>front3</h1>\r\n");
      out.write("            <div class=\"pageFoldRight\"></div></div>\r\n");
      out.write("          <div class=\"pageFace back\"><h1>back3</h1>\r\n");
      out.write("            <div class=\"pageFoldLeft\"></div></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"page2\" class=\"page\">\r\n");
      out.write("          <div class=\"pageFace front\"><h1>front2</h1>\r\n");
      out.write("            <div class=\"pageFoldRight\"></div></div>\r\n");
      out.write("          <div class=\"pageFace back\"><h1>back2</h1>\r\n");
      out.write("            <div class=\"pageFoldLeft\"></div></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"page1\" class=\"page\">\r\n");
      out.write("          <div class=\"pageFace front\"><h1>front1</h1>\r\n");
      out.write("            <div class=\"pageFoldRight\"></div></div>\r\n");
      out.write("          <div class=\"pageFace back\"><h1>back1</h1>\r\n");
      out.write("            <div class=\"pageFoldLeft\"></div></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
